// ------------------------------------------------------------
// FeatureCodegen.cs
// Author : WizardHeHeJun
// Created: 2026-07-04
// ------------------------------------------------------------
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Ciga.AnchorHorror.EditorTools
{
    /// <summary>
    /// AnchorFeatures.csv → 确定性生成 FeatureEnums.Generated.cs + FeatureTag.Generated.cs，并回填 FeatureDatabase.asset。
    /// 触发：菜单 Ciga/AnchorHorror/从CSV生成特征（另有「校验生成往返一致」）。
    /// 确定性：维度按 dimId、取值按 valueId 升序；成员显式 = valueId；None 恒第 0 成员；固定 \n；写前逐字节比对无变化不写（保 .meta）。
    /// </summary>
    public static class FeatureCodegen
    {
        public const string CsvPath = "Assets/Res/AnchorHorror/AnchorFeatures.csv";
        public const string EnumsPath = "Assets/Scripts/AnchorHorror/Core/FeatureEnums.Generated.cs";
        public const string TagPath = "Assets/Scripts/AnchorHorror/Feature/FeatureTag.Generated.cs";
        public const string DbPath = "Assets/Res/AnchorHorror/FeatureDatabase.asset";

        private static readonly Color GoldKeyword = new Color(1f, 0.85f, 0.4f);

        [MenuItem("Ciga/AnchorHorror/从CSV生成特征")]
        public static void RegenerateMenu()
        {
            try
            {
                int written = RegenerateAll();
                AssetDatabase.Refresh();
                EditorUtility.DisplayDialog("特征生成", written > 0
                    ? $"已从 CSV 生成/回填（{written} 处写盘）。等待编译完成。"
                    : "CSV 无变化，生成物已是最新（未写盘）。", "好");
            }
            catch (FeatureCsvException ex)
            {
                EditorUtility.DisplayDialog("特征生成失败（CSV 校验）", ex.Message, "去修表");
            }
        }

        [MenuItem("Ciga/AnchorHorror/校验生成往返一致")]
        public static void VerifyRoundtripMenu()
        {
            try
            {
                var data = ParseCsvFile();
                string e1 = GenerateEnumsText(data);
                string e2 = GenerateEnumsText(data);
                string t1 = GenerateFeatureTagText(data);
                string t2 = GenerateFeatureTagText(data);
                bool ok = e1 == e2 && t1 == t2
                          && Normalize(ReadOrEmpty(EnumsPath)) == e1
                          && Normalize(ReadOrEmpty(TagPath)) == t1;
                EditorUtility.DisplayDialog("往返一致校验",
                    ok ? "一致：连续两次生成逐字节相同，且磁盘产物与之相符。"
                       : "不一致：磁盘产物与当前 CSV 生成结果有差异，请重新生成。", "好");
            }
            catch (FeatureCsvException ex)
            {
                EditorUtility.DisplayDialog("往返校验失败（CSV 校验）", ex.Message, "去修表");
            }
        }

        /// <summary>解析+校验+生成+回填。返回写盘处数（0=全无变化）。校验失败抛 FeatureCsvException。</summary>
        public static int RegenerateAll()
        {
            var data = ParseCsvFile();
            int written = 0;
            if (WriteIfChanged(EnumsPath, GenerateEnumsText(data)))
            {
                written++;
            }

            if (WriteIfChanged(TagPath, GenerateFeatureTagText(data)))
            {
                written++;
            }

            if (FillDatabase(data))
            {
                written++;
            }

            return written;
        }

        /// <summary>解析 CSV 并回填 FeatureDatabase.asset（供 AnchorHorrorSetup.BuildAll 复用，单一真源）。校验失败抛 FeatureCsvException。</summary>
        public static bool FillDatabaseFromCsv()
        {
            return FillDatabase(ParseCsvFile());
        }

        private static FeatureCsvData ParseCsvFile()
        {
            string full = Path.Combine(Directory.GetCurrentDirectory(), CsvPath);
            if (!File.Exists(full))
            {
                throw new FeatureCsvException($"找不到 CSV：{CsvPath}");
            }

            return FeatureCsvParser.Parse(File.ReadAllText(full));
        }

        // ---------------------------------------------------------------- 枚举生成

        public static string GenerateEnumsText(FeatureCsvData data)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated> 由 ").Append(CsvPath).Append(" 生成，请勿手改。\n");
            sb.Append("//   改值 / 改维度：编辑该 CSV → 菜单 Ciga/AnchorHorror/从CSV生成特征。\n");
            sb.Append("//   成员显式 = valueId（与 FeatureUnit 的 int 值一致）；None 恒为第 0 成员。\n");
            sb.Append("// ------------------------------------------------------------\n");
            sb.Append("// FeatureEnums.Generated.cs   Author : WizardHeHeJun (generated)\n");
            sb.Append("// ------------------------------------------------------------\n\n");
            sb.Append("namespace Ciga.AnchorHorror\n{\n");

            // FeatureDimension
            sb.Append("    /// <summary>特征维度（生成自 CSV @dim 行）。</summary>\n");
            sb.Append("    public enum FeatureDimension\n    {\n");
            foreach (var dim in data.SortedDims())
            {
                sb.Append("        ").Append(dim.Key).Append(" = ").Append(dim.Id).Append(",\n");
            }

            sb.Append("    }\n");

            // 每维度值枚举
            foreach (var dim in data.SortedDims())
            {
                sb.Append("\n    /// <summary>").Append(dim.Key).Append(" 维度取值（生成自 CSV）。</summary>\n");
                sb.Append("    public enum Feature").Append(dim.Key).Append("\n    {\n");
                sb.Append("        None = 0,\n");
                foreach (var v in data.ValuesOf(dim.Id))
                {
                    sb.Append("        ").Append(v.EnumMember).Append(" = ").Append(v.ValueId).Append(",\n");
                }

                sb.Append("    }\n");
            }

            sb.Append("}\n");
            return sb.ToString();
        }

        // ---------------------------------------------------------------- FeatureTag partial 生成

        public static string GenerateFeatureTagText(FeatureCsvData data)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated> 由 ").Append(CsvPath).Append(" 生成，请勿手改。\n");
            sb.Append("//   每维度一个 typed [SerializeField] 字段 + 只读属性；BuildFeaturesGenerated 逐维度装配 FeatureUnit。\n");
            sb.Append("//   加维度 = 编辑 CSV → 菜单生成（本文件与 FeatureTag.cs 须同提交）。\n");
            sb.Append("// ------------------------------------------------------------\n");
            sb.Append("// FeatureTag.Generated.cs   Author : WizardHeHeJun (generated)\n");
            sb.Append("// ------------------------------------------------------------\n");
            sb.Append("using System.Collections.Generic;\n");
            sb.Append("using UnityEngine;\n\n");
            sb.Append("namespace Ciga.AnchorHorror\n{\n");
            sb.Append("    public partial class FeatureTag\n    {\n");
            sb.Append("        [Header(\"特征维度（由 AnchorFeatures.csv 生成）\")]\n");

            var dims = data.SortedDims();
            foreach (var dim in dims)
            {
                sb.Append("        [SerializeField] private Feature").Append(dim.Key)
                    .Append(" ").Append(FieldName(dim.Key)).Append(";\n");
            }

            foreach (var dim in dims)
            {
                sb.Append("\n        /// <summary>").Append(dim.Key).Append(" 特征。</summary>\n");
                sb.Append("        public Feature").Append(dim.Key).Append(" ").Append(dim.Key)
                    .Append(" => ").Append(FieldName(dim.Key)).Append(";\n");
            }

            sb.Append("\n        /// <summary>逐维度把当前枚举值装配进 buffer（None 也加入，匹配侧按 IsNone 剔除）。</summary>\n");
            sb.Append("        partial void BuildFeaturesGenerated(List<FeatureUnit> buffer)\n        {\n");
            foreach (var dim in dims)
            {
                sb.Append("            buffer.Add(new FeatureUnit(FeatureDimension.").Append(dim.Key)
                    .Append(", (int)").Append(FieldName(dim.Key)).Append("));\n");
            }

            sb.Append("        }\n");
            sb.Append("    }\n}\n");
            return sb.ToString();
        }

        // ---------------------------------------------------------------- FeatureDatabase 回填（就地重建 _entries，保 GUID）

        public static bool FillDatabase(FeatureCsvData data)
        {
            var db = AssetDatabase.LoadAssetAtPath<FeatureDatabase>(DbPath);
            if (db == null)
            {
                Debug.LogWarning($"[FeatureCodegen] 找不到 FeatureDatabase：{DbPath}，跳过回填。");
                return false;
            }

            var so = new SerializedObject(db);
            var entries = so.FindProperty("_entries");
            if (entries == null)
            {
                Debug.LogWarning("[FeatureCodegen] FeatureDatabase 无 _entries 字段，跳过回填。");
                return false;
            }

            entries.ClearArray();
            int idx = 0;
            foreach (var dim in data.SortedDims())
            {
                foreach (var v in data.ValuesOf(dim.Id))
                {
                    entries.InsertArrayElementAtIndex(idx);
                    var e = entries.GetArrayElementAtIndex(idx);
                    e.FindPropertyRelative("_dimension").enumValueIndex = dim.Id;
                    e.FindPropertyRelative("_value").intValue = v.ValueId;
                    e.FindPropertyRelative("_displayName").stringValue = v.DisplayNameZh;

                    Color keyword = GoldKeyword;
                    if (!string.IsNullOrEmpty(v.ColorHex))
                    {
                        ColorUtility.TryParseHtmlString(v.ColorHex, out keyword);
                    }

                    e.FindPropertyRelative("_keywordColor").colorValue = keyword;

                    AudioClip clip = null;
                    if (FeatureCsvParser.ResolveAudioPath(v.AudioGuid, out string audioPath))
                    {
                        clip = AssetDatabase.LoadAssetAtPath<AudioClip>(audioPath);
                    }

                    e.FindPropertyRelative("_clip").objectReferenceValue = clip;
                    idx++;
                }
            }

            if (!so.hasModifiedProperties)
            {
                return false;
            }

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(db);
            AssetDatabase.SaveAssetIfDirty(db);
            return true;
        }

        // ---------------------------------------------------------------- helpers

        /// <summary>dimKey → 字段名（"Color" → "_color"），与手写 FeatureTag 契约一致。</summary>
        private static string FieldName(string dimKey)
        {
            return "_" + char.ToLowerInvariant(dimKey[0]) + dimKey.Substring(1);
        }

        private static bool WriteIfChanged(string assetPath, string content)
        {
            string full = Path.Combine(Directory.GetCurrentDirectory(), assetPath);
            string normalized = content.Replace("\r\n", "\n");
            if (File.Exists(full) && Normalize(File.ReadAllText(full)) == normalized)
            {
                return false;
            }

            File.WriteAllText(full, normalized, new UTF8Encoding(false));
            return true;
        }

        private static string ReadOrEmpty(string assetPath)
        {
            string full = Path.Combine(Directory.GetCurrentDirectory(), assetPath);
            return File.Exists(full) ? File.ReadAllText(full) : string.Empty;
        }

        private static string Normalize(string s)
        {
            return s.Replace("\r\n", "\n").Replace("\r", "\n");
        }
    }
}
