// <auto-generated> 由 Assets/Res/AnchorHorror/AnchorFeatures.csv 生成，请勿手改。
//   每维度一个 typed [SerializeField] 字段 + 只读属性；BuildFeaturesGenerated 逐维度装配 FeatureUnit。
//   加维度 = 编辑 CSV → 菜单生成（本文件与 FeatureTag.cs 须同提交）。
// ------------------------------------------------------------
// FeatureTag.Generated.cs   Author : WizardHeHeJun (generated)
// ------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;

namespace Ciga.AnchorHorror
{
    public partial class FeatureTag
    {
        [Header("特征维度（由 AnchorFeatures.csv 生成）")]
        [SerializeField] private FeatureColor _color;
        [SerializeField] private FeatureShape _shape;
        [SerializeField] private FeatureMaterial _material;
        [SerializeField] private FeatureTexture _texture;
        [SerializeField] private FeatureSound _sound;

        /// <summary>Color 特征。</summary>
        public FeatureColor Color => _color;

        /// <summary>Shape 特征。</summary>
        public FeatureShape Shape => _shape;

        /// <summary>Material 特征。</summary>
        public FeatureMaterial Material => _material;

        /// <summary>Texture 特征。</summary>
        public FeatureTexture Texture => _texture;

        /// <summary>Sound 特征。</summary>
        public FeatureSound Sound => _sound;

        /// <summary>逐维度把当前枚举值装配进 buffer（None 也加入，匹配侧按 IsNone 剔除）。</summary>
        partial void BuildFeaturesGenerated(List<FeatureUnit> buffer)
        {
            buffer.Add(new FeatureUnit(FeatureDimension.Color, (int)_color));
            buffer.Add(new FeatureUnit(FeatureDimension.Shape, (int)_shape));
            buffer.Add(new FeatureUnit(FeatureDimension.Material, (int)_material));
            buffer.Add(new FeatureUnit(FeatureDimension.Texture, (int)_texture));
            buffer.Add(new FeatureUnit(FeatureDimension.Sound, (int)_sound));
        }
    }
}
