// <auto-generated> 由 Assets/Res/AnchorHorror/AnchorFeatures.csv 生成，请勿手改。
//   改值 / 改维度：编辑该 CSV → 菜单 Ciga/AnchorHorror/从CSV生成特征。
//   成员显式 = valueId（与 FeatureUnit 的 int 值一致）；None 恒为第 0 成员。
// ------------------------------------------------------------
// FeatureEnums.Generated.cs   Author : WizardHeHeJun (generated)
// ------------------------------------------------------------

namespace Ciga.AnchorHorror
{
    /// <summary>特征维度（生成自 CSV @dim 行）。</summary>
    public enum FeatureDimension
    {
        Color = 0,
        Shape = 1,
        Material = 2,
        Texture = 3,
        Sound = 4,
    }

    /// <summary>Color 维度取值（生成自 CSV）。</summary>
    public enum FeatureColor
    {
        None = 0,
        Red = 1,
        Blue = 2,
        Green = 3,
        Yellow = 4,
        White = 5,
        Black = 6,
        Brown = 7,
        Beige = 8,
        Transparent = 9,
        LightGray = 10,
        DarkBrown = 11,
        DarkRed = 12,
        WarmYellow = 13,
        Gold = 14,
        Gray = 15,
        DarkGray = 16,
        Colorful = 17,
        Silver = 18,
    }

    /// <summary>Shape 维度取值（生成自 CSV）。</summary>
    public enum FeatureShape
    {
        None = 0,
        Round = 1,
        Square = 2,
        Long = 3,
        Flat = 4,
        Irregular = 5,
        Curved = 6,
        Cone = 7,
    }

    /// <summary>Material 维度取值（生成自 CSV）。</summary>
    public enum FeatureMaterial
    {
        None = 0,
        Wood = 1,
        Metal = 2,
        Glass = 3,
        Fabric = 4,
        Paper = 5,
        Ceramic = 6,
        Plastic = 7,
        Stone = 8,
        WoodGlass = 9,
        GlassMetal = 10,
        MetalPlastic = 11,
    }

    /// <summary>Texture 维度取值（生成自 CSV）。</summary>
    public enum FeatureTexture
    {
        None = 0,
        Smooth = 1,
        Rough = 2,
        Glossy = 3,
        Matte = 4,
        Patterned = 5,
        Soft = 6,
        SoftLight = 7,
        Reflective = 8,
        Peeling = 9,
        Fiber = 10,
        Worn = 11,
        Wet = 12,
        Scaled = 13,
        PaintPeeled = 14,
        Cracked = 15,
        Broken = 16,
        Fissure = 17,
        Scratched = 18,
    }

    /// <summary>Sound 维度取值（生成自 CSV）。</summary>
    public enum FeatureSound
    {
        None = 0,
        ClothTouch = 1,
        WoodFriction = 2,
        LightHum = 3,
        GlassClink = 4,
        Ticking = 5,
        MetalMechanical = 6,
        PlasticClick = 7,
    }
}
